module.exports = {
    STATUS: {
        UP: 'up',
        DOWN: 'down',
    },
    CLOUDFRONT_DISTRIBUTION_DOMAIN: process.env.CLOUDFRONT_DISTRIBUTION_DOMAIN,
    DYNAMO_DB: process.env.DYNAMO_DB,
    AWS_REGION: process.env.AWS_REGION,
    S3_ASSETS_BUCKET_NAME: process.env.S3_ASSETS_BUCKET_NAME,
    TOPIC_ARN: process.env.TOPIC_ARN,
    URLS: process.env.DOMAINS || [
        'https://24apotek.mementor.no',
        'https://adminsenter.no',
        'https://baroniet.no',
        'https://brand.ortopro.no',
        'https://cdsp.mementor.no',
        'https://cyclingnorway.no',
        'https://easydays.me',
        'https://eavisa.com',
        'https://elfremdrift.no',
        'https://fiddle.mementor.no',
        'https://helgelandbetong.no',
        "http://24apotek.mementor.no",
        "http://adminsenter.no",
        "http://baroniet.no",
        "http://brand.ortopro.no",
        "http://cdsp.mementor.no",
        "http://cyclingnorway.no",
        "http://easydays.me",
        "http://eavisa.com",
        "http://elfremdrift.no",
        "http://freshnutri.no",
        "http://helgelandbetong.no",
        "http://helgelandholding.no",
        "http://helmar.no",
        "http://hjortconveyor.no",
        "http://hpf.no",
        "http://hvitetenner.net",
        "http://iapoteket.no",
        "http://idrettskultur.mementor.no",
        "http://in.mementor.no",
        "http://iopt2018.mementor.no",
        "http://iopt.no",
        "http://iwp.mementor.no",
        "http://klesarven.no",
        "http://kongsvold.no",
        "http://landstil.com",
        "http://latterkula.no",
        "http://lattermuskelen.com",
        "http://mementor.no",
        "http://mkompetanse.no",
        "http://morsommeprodukter.no",
        "http://movitec.no",
        "http://natureventyr.no",
        "http://nbr.no",
        "http://norfinance.no",
        "http://norseomega.mementor.no",
        "http://nyhetsbrev.mementor.no",
        "http://onlinecasinomonkeys.com",
        "http://onlinecasinomonsters.com",
        "http://ortopro.no",
        "http://pinkfish.no",
        "http://pinkfloydnorway.com",
        "http://polarcamp.no",
        "http://politiet.mementor.no",
        "http://probat.no",
        "http://qr-kode.no",
        "http://rettadvokat.no",
        "http://robito.mementor.no",
        "http://robito.no",
        "http://smartrepairbilpleie.no",
        "http://snomann.no",
        "http://sport.mementor.no",
        "http://spsh.no",
        "http://studiovestland.no",
        "http://v2.mementor.no",
        "http://viralefilmer.no",
        "http://wc.mementor.no"
    ]
}